# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-workflow-1-in-local-repo:
    uses: github.com/BackNot/core/.github/workflows/reusable.yml@415c9245e6ebf7c3d0d83188f830a4fcf2f24136
    with:
      language: es
