name: Create new translation version branch

on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: 'The core repository branch to pull translation YAML files from'
        required: true
      new_branch_name:
        description: 'The name of the new branch to create in this repository with the pulled files'
        required: true

jobs:
  pull_and_create_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3
      - name: Set up Git with GitHub Actions bot identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Pull content from another repository
        run: |
          git clone --branch ${{ inputs.source_branch }} --single-branch https://github.com/BackNot/core temp-repo
          rm -rf temp-repo/.git
          rsync -a --exclude='.git' temp-repo/ .
      - name: Create a new branch with the pulled content
        run: |
          git checkout -b ${{ inputs.new_branch_name }}
          git add model
          git commit -m "Pulled content from ${{ inputs.source_repo }}:${{ inputs.source_branch }}"
          git push origin ${{ inputs.new_branch_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
