# This is the workflow which will call the shared workflow which will clone the english model files

name: Get English files

# Controls when the workflow will run
on:
  workflow_dispatch:
     inputs:
      source_branch:
        description: 'The core repository branch to pull translation YAML files from (e.g. develop)'
        required: true
      source_folder:
        description: 'The folder in the core branch to pull translation YAML files from (e.g. model)'
        required: true
      new_branch_name:
        description: 'The name of the new branch to create in this repository with the pulled files (e.g. trans_2.0.8)'
        required: true

jobs:
  shared-workflow:
    uses: BackNot/core/.github/workflows/blank.yml@d8ddbd2e447ee24bbcd4a15472dd57c60834285b
    with:
      source_branch: ${{inputs.source_branch}}
      source_folder: ${{inputs.source_folder}}
      new_branch_name: ${{inputs.new_branch_name}}
